#!/bin/bash
. /etc/sfj/sfjconf.sh

LOGFILE=/var/tmp/sfj1st.log

echo "=======================================" >> ${LOGFILE}
date >> ${LOGFILE}

REPLY=`sfjconvx2j $1 2>> ${LOGFILE}`
if [ $? -ne 0 ]
then
	echo ${REPLY} >> ${LOGFILE}
	echo "ERROR : CAN NOT Convert xlsx file to JSON file!"
	echo "        Pleas check ${LOGFILE}"
	exit 1
fi
echo ${REPLY} >> ${LOGFILE}
PRONAME=`echo ${REPLY} | awk '{print $3}'`

sfjmovep2d ${PRONAME} >> ${LOGFILE} 2>&1
if [ $? -ne 0 ]
then
	echo "ERROR : CAN NOT Move xlsx file to ${GITREPODIR} !"
	echo "        Pleas check ${LOGFILE}"
	exit 2
fi

sfjmakej2p ${PRONAME} 1>> ${LOGFILE} 2>&1
if [ $? -ne 0 ]
then
	echo "ERROR : CAN NOT Move JSON file file to Paramater files !"
	echo "        Pleas check ${LOGFILE}"
	exit 3
fi

KPW=${PWD}
cd /var/sfj/gitrepo/${PRONAME}

terraform apply -var-file=sfjpara.tfvars 2>&1 | tee -a  ${LOGFILE}
if [ $? -ne 0 ]
then
	echo "ERROR : CAN NOT Apply to CLOUD !"
	echo "        Pleas check ${LOGFILE}"
	exit 9
fi

cd ${KPW}

#
