#!/bin/bash

if [ "$1" == "" ]
then
	echo "no project name"
	exit 1
fi

. /etc/sfj/sfjconf.sh
KPWD=${PWD}
PN=$1

cd ${GITREPODIR}/${PN}

terraform apply -var-file=sfjpara.tfvars -no-color
RET=$?

if [ ${RET} -ne 0 ]
then
        exit ${RET}
fi

cd ${KPWD}

exit 0

#
