#!/bin/bash

. /etc/sfj/sfjconf.sh

KPWD=${PWD}
PNAME=$1
DBG=$2

if [ "${PNAME}" == "" ]
then
	echo "NO Prohect Name"
	exit 201
fi

cd ${UPLOADDIR}

FILE=`ls -1t | tail -1`
if [ "${FILE}" == "" ]
then
	echo "NO Filename"
	exit 202
fi

sudo chown -R ${SFJUSER}.${SFJUSER} ${GITREPODIR}/${PNAME}
sudo chmod -R 0777 ${GITREPODIR}/${PNAME}
mkdir -p ${GITREPODIR}/${PNAME}/xlsfile

echo "mv -f ${UPLOADDIR}/${FILE} ${GITREPODIR}/${PNAME}/xlsfile/${FILE}"
mv -f ${UPLOADDIR}/${FILE} ${GITREPODIR}/${PNAME}/xlsfile/${FILE}

cd ${KPWD}

exit 0
#
