# Install Zabbix-agent
- name: Download and install Zabbix-agent Repo version 6
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"
  ignore_errors: True

- name: Download and install Zabbix-agent Repo version 7
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"
  ignore_errors: True

- name: Check Zabbix-agent
  package: name=zabbix-agent state=latest
  register: result_zbx
  ignore_errors: True

- name: Set Server ip and Hostname
  lineinfile: >
    dest=/etc/zabbix/zabbix_agentd.conf
    state=present
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
  - regexp: '^Hostname=.*$'
    line: 'Hostname={{ inventory_hostname }}'
  - regexp: '^Server=.*$'
    line: 'Server={{ ansible_server_ip }}'
  - regexp: '^ServerActive=.*$'
    line: 'ServerActive={{ ansible_server_ip }}'

- name: Restart Zabbix-agent
  service: name=zabbix-agent state=restarted enabled=yes
  ignore_errors: True

